config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'cars#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'dashboard', to: 'pages#dashboard'
  resources :cars, except: [:edit, :update] do
    resources :bookings, only: [:show, :new, :create]
  end
  resources :bookings, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :bookings, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /articles
  def index
    @bookings = Booking.all
  end

  # GET /articles/1
  def show
  end


  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @booking = Booking.new(booking_params)
    @car = Car.find(params[:car_id]) #ici on va rattacher la voiture actuelle au booking
    @booking.car = @car
    @booking.user = current_user
    @booking.total_price = @car.price_per_day * (@booking.end_date - @booking.start_date).to_i
    if @booking.save
      redirect_to car_booking_path(@car, @booking), notice: 'Booking was successfully created.'
    else
      render "cars/show" # carS car ca appelle le controller
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @booking.destroy
    redirect_to bookings_url, notice: 'Booking was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def booking_params
      params.require(:booking).permit(:start_date, :end_date, :user_id, :car_id)
    end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /articles
  def index
    @cars = Car.all
  end

  # GET /articles/1
  def show
    @car = Car.find(params[:id])
    @booking = Booking.new
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def dashboard
    if current_user
      @bookings = Booking.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<div class="card" style="width: 18rem;">
  <%= image_tag ("#{@booking.car.url_car}"), class: "card-img-top"%>
  <div class="card-body">
    <h5 class="card-title">Réservation</h5>
    <%=  %>

    <p class="card-text"><%=  %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><%= @booking.car.model %></li>
    <li class="list-group-item"><%= @booking.start_date %> - <%= @booking.end_date %></li>
    <li class="list-group-item"><%= @booking.total_price%> €</li>
    <li class="list-group-item"><%= @booking.user.name %></li>
  </ul>
</div>

app/views/cars/index.html.erb
<div class="container">
  <div class="row">
    <% @cars.each do |car| %>
      <div class="col-sm-4">
        <div class="card" style="width: 24rem;">
          <%= image_tag ("#{car.url_car}"), class: "card-img-top"%>
          <div class="card-body">
            <h5 class="card-title"><%= car.model %></h5>
            <p class="card-text"> <%= car.brand %></p>
            <h6 class="card-title"> <%=  car.price_per_day %> €</h6>
            <%= link_to "Book these car now!", car_path(car), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/cars/show.html.erb
<div class="booking container d-flex justify-content-space-between p-2 m-5 pt-5 shadow-sm p-3 mb-5 bg-white rounded">
  <div>
      <div><%= image_tag ("#{@car.url_car}"), class: "card-img-top"%></div>
  </div>
  <div class="col-sm-12 w-50 p-3">
    <%= simple_form_for [ @car, @booking ] do |f| %>
      <%= f.input :start_date, label: "Date de début" %>
      <%= f.input :end_date, label: "Date de fin" %>
      <p>Prix total : <%= @car.price_per_day%> € par jour</p>
      <%= f.submit "Réserve ta voiture", class: "bouton_reserver" %>


    <% end %>
  <%= link_to "Retour", car_path(@car), class:"btn btn-lg btn-secondary mt-5 .text-center"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarRentals</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container_dash text-center">
  <h1>DASHBOARD</h1>
  <div class="infos m-5">
    <h2><%= current_user.firstname %> <%= current_user.name %></h2>
  </div>

  <% @bookings.each do |booking| %>
    <div class="card" style="width: 18rem;">
      <%= image_tag ("#{booking.car.url_car}"), class: "card-img-top"%>
      <div class="card-body">
        <h5 class="card-title"><%= booking.car.model %></h5>
        <p class="card-text"> <%= booking.car.brand %></p>
        <h6 class="card-title"> <%=  booking.total_price %> €</h6>
      </div>
    </div>
  <%end%>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to " http://localhost:3000/", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
             <a href="/dashboard">Messages </a>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>